### ISSUE TITLE
这个是不是会把appid和secret都暴露给客户端？

### ISSUE THREAD

**Issue by s524797336** [borenXue/webpack-alioss-plugin#3]
如果会的话会不会造成安全隐患？

**Comment by borenXue** [comment]
新增了对环境变量的支持

如果不设置`accessKeyId`则会使用环境中的 `WEBPACK_ALIOSS_PLUGIN_ACCESS_KEY_ID`变量。
`accessKeySecret ` 与 `WEBPACK_ALIOSS_PLUGIN_ACCESS_KEY_SECRET` 同理。
可参考 `README.md` 来设置。

更新到最新版本即可使用

**Comment by bowencool** [comment]
在.gitignore文件中忽略
```
+   config/secret.js
```
