### ISSUE TITLE
service-worker.js文件没有上传

### ISSUE THREAD

**Issue by bowencool** [borenXue/webpack-alioss-plugin#4]
![image](https://user-images.githubusercontent.com/20217146/40585823-7e9e0146-61eb-11e8-9df8-8432e0f52e5a.png)
使用的是[sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin)生成的
```
    "webpack": "^3.6.0",
    "webpack-alioss-plugin": "^1.4.6",
    "sw-precache-webpack-plugin": "^0.11.5"
```

**Comment by borenXue** [comment]
需要将该文件移至打包目录, eg: dist
