### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by xsteadybcgo** [borenXue/webpack-alioss-plugin#6]
建议添加分片上传，断点上传，上传错误重试的配置功能选项。

**Comment by borenXue** [comment]
很好的建议, 已进行以下优化, 可更新到 [`v2.2.1`](https://github.com/borenXue/webpack-alioss-plugin/releases) 体验:

* 上传失败后自动重试
* 上传前检测是否已存在
* gzip 压缩后再上传

考虑到打包后的 js 文件体积不会太大, `断点续传`并非硬需求, 所以暂不支持。(文件gzip体积超过5、6百KB的时候就应该考虑修改脚本来减少体积了)
后续如果还有类似的建议再考虑支持
