### ISSUE TITLE
上传前检测存在不准确

### ISSUE THREAD

**Issue by berudomon** [borenXue/webpack-alioss-plugin#9]
你好，我开启了上传前检测，然后有一些文件没有上传，在你的代码里添加了打印，发现上传检测不准确。
![image](https://user-images.githubusercontent.com/20949511/72239716-dd6b4380-361c-11ea-9de7-e3a3e6b338c8.png)

例如已经上传了文件res-test/frontend/80.5629b26986735bed6373.chunk.js.LICENSE，
然后再上传res-test/frontend/80.5629b26986735bed6373.chunk.js 
调用oss的 client.list 依然有返回，但是你的代码没有进一步判断文件名是否一致。

![image](https://user-images.githubusercontent.com/20949511/72239860-4d79c980-361d-11ea-87cc-5f4c335e3d0c.png)

**Comment by berudomon** [comment]
已排查不是

**Comment by borenXue** [comment]
已修复 @berudomon 

更新到 2.2.6 即可, 现在会严格检测文件名是否一致
